### ISSUE TITLE
Youtube videos

### ISSUE THREAD

**Issue by scottolsen** [stevo/colorbox-rails#27]
Playing around with youtube vids and haven't been able to get one to work. Is it possible to with this gem?

**Comment by TylerSangster** [comment]
Here is an example of mine

  = link_to (image_tag youtube_image(@asset.video_url),width: 300 ), embed(@asset.video_url), rel: 'photos', data: {colorbox_static: true, colorbox_title: @asset.name, colorbox_height: '480', colorbox_width: '854', colorbox_iframe: true  }

  = link_to (image_tag IMAGE, embed_URL, rel: 'Group name', data: { colorbox_static: true, colorbox_title: @asset.name, colorbox_height: '50%', colorbox_width: '80%', colorbox_iframe: true  }
